/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fanorona.Gui;

import fanorona.Logic.Board;
import static fanorona.Logic.Board.COLS;
import static fanorona.Logic.Board.SPACE;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import static fanorona.Logic.Board.cellSize;
import fanorona.Logic.Move;
import fanorona.Logic.Player;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;
import sun.swing.SwingUtilities2;


/**
 *
 * @author galbenozilio
 */
public class GamePanel extends javax.swing.JPanel {
    
    Image imageBoard;
    Board board; 
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        imageBoard = Toolkit.getDefaultToolkit().getImage("images/Empty_Board.png");
        this.board = new Board(this);
    }
    
    @Override
    public void paint(Graphics gr){
        gr.drawImage(imageBoard, 0, 0,this.getWidth(), this.getHeight(), this);
        board.paint(gr);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                formMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMousePressed
    {//GEN-HEADEREND:event_formMousePressed
        int row = (evt.getY() - Board.DIF) / (Board.cellSize+Board.SPACE);
        int col = (evt.getX() - Board.DIF) / (Board.cellSize + Board.SPACE);
        board.Click(row,col);
        repaint();
        board.getOneMoreMove();
        if(board.startAi == true)
        {
            new Thread(){ 	//Creating an object of Anonymous class that extends Thread class
                public void run()	//Anonymous class overriding run() method of Thread class
                {
                    try
                    {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex)
                    {
                        Logger.getLogger(GamePanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    // Delete
                    System.out.println("");
                    System.out.println("");
                    System.out.println("The move I did: ");
                    Move m = board.startAi();
                    System.out.println("from: " + m.getFrom());
                    System.out.println("to: " + m.getTo());
                    System.out.println("capture: "+ m.getCapture());
                    long from, to;
                    Player cur, op;
                    from = m.getFrom();
                    to = m.getTo();
                    cur = board.turn.equals("pw") ? board.getWhite():board.getBlack();
                    op = board.turn.equals("pw") ? board.getBlack():board.getWhite();
                    long x = from;
                    x = ~x;
                    cur.state &= x;
                    cur.state |= to;
                    op.state ^= m.getCapture();
                    repaint();
                    while (m.getExtraCapture() != null)
                    {
                        try
                        {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex)
                        {
                            Logger.getLogger(GamePanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        //board.selected = m.getTo();
                        m = m.getExtraCapture();
                        x = m.getFrom();
                        x = ~x;
                        cur.state &= x;
                        cur.state |= m.getTo();
                        op.state ^= m.getCapture();
                        repaint();
                        System.out.println("");
                        System.out.println("from: "+ m.getFrom());
                        System.out.println("to: " + m.getTo());
                        System.out.println("capture: "+ m.getCapture());
                        //selected = 0;
                        //panel.repaint();
                    }
                    if(m.getCapture() == 0)
                        board.tie++;
                    else
                        board.tie = 0;
                    board.depth = 5;
                    board.turn = board.turn.equals("pw") ? "pb" : "pw";
                    board.startAi = false;
                }
            }.start(); 
        }
        board.checkWin();
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
